algoritmo "Operadores relacionais." //verdadeiro ou falso.
// Função :
// Autor :
// Data : 20/07/2021
// Seção de Declarações 
var
a,b,c:inteiro
inicio
//Operadores relacionais vão testar a relação entre variáveis, valores ou expressões.
//Ex.: a<b, a>b, a>=b, a=2, (c=a+b), (c=b^a), (b=c%2), (1=c%2).
//Ex. de variáveis: a=b.
//Ex. de valores: a>2.
//Ex. de expressões: c=a+b. O sinal '+' irá somar se 'a+b' é = a 'c'.
//Ex. mistos: b<=c%2, 1=c%2
a<-2
b<-3
c<-5
Escreva (a>=2)
fimalgoritmo
